# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Binder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Binder
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SwipeCellKit'

end
